git:
  submodules: false

before_script:
    - git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
    - go get -u -v github.com/spf13/hugo

script:
    - hugo

notifications:
  slack: ruhm-pacino:vcSqblVd1vSDgaOzWLNbThfS