baseurl = "http://blog.ruhm.me/"
title = "Data Portal"
languageCode = "en-us"
copyright = "Alastair Ruhm"
Paginate = 20
metaDataFormat = "toml"

[Author]
    name = "Alastair Ruhm"
    profile = "https://google.com/+XXX"

[taxonomies]
    tag = "tags"
    category = "categories"


[Params]
    intro = true
    headline = "Data Portal"
    description = "黑色天使羽毛，使群星都黯淡无光"
    github = "https://github.com/alastairruhm"
    linkedin = "https://linkedin.com/in/XXX/"
    gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/Ruhm_ST"
    stackoverflow = "http://stackoverflow.com/users/XXX/YYY"

[Permalinks]
    post = "/:filename/"

[menu]

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "weekly-issues"
    url = "/weekly-issues/"
    weight = 2

[[menu.main]]
    name = "awesome-list"
    url = "/awesome-list/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 5

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 6